import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import { Toaster } from "@/components/ui/sonner";
import OAuthTokenSync from "@/components/OAuthTokenSync";
import { SessionProvider } from "next-auth/react";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
	title: "WebChat",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{/* <SessionProvider>
					<AppProvider>
						<OAuthTokenSync />
						{children}
					</AppProvider>
					<Toaster position="top-center" richColors />
				</SessionProvider> */}
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
