import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "WebChat",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AppProvider>{children}</AppProvider>
				<Toaster position="top-center" richColors />
			</body>
		</html>
	);
}
